CloudX_Test/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^$',views.index,name='index'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

accounts/urls.py
from django.conf.urls import url
from accounts import views
# SET THE NAMESPACE!
app_name = 'accounts'
urlpatterns=[
    url(r'^signup/$',views.signup,name='register'),
    url(r'^login/$',views.user_login,name='user_login'),
    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    phone_number = models.CharField(blank=True,max_length=13)
    def __str__(self):
        """
        :return: user's username
        """
        return self.user.username

accounts/forms.py
from django import forms
from accounts.models import UserProfileInfo
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('first_name','last_name','password','email')
class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('phone_number',)

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from accounts.forms import UserForm,UserProfileInfoForm
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    """
    :param request:
    :return: returns rendered html template with welcome message including an username if the user is logged in
             and if not so returns rendered html asking user to register or log in
             and if any exception raises returns an internal server error with the error
    """
    try:
        return render(request,'accounts/index.html')
    except Exception as e:
        return HttpResponse(e, status=500)


def signup(request):
    """
    performs registration of the user through forms
    :param request: includes user attributes from user form i.e first_name, last_name, email, password
    :return: returns the success if the user is registered successfully and forms is valid else returns to the user form
    """
    try:
        registered = False
        if request.method == 'POST':
            user_form = UserForm(data=request.POST)
            user_form.username = request.POST['email']
            profile_form = UserProfileInfoForm(data=request.POST)
            if user_form.is_valid() and profile_form.is_valid():
                user = User()
                user.first_name = request.POST.get('first_name')
                user.last_name = request.POST.get('last_name')
                user.email = request.POST.get('email')
                user.username = request.POST.get('email')
                user.set_password(request.POST.get('password'))
                user.save()
                profile = profile_form.save(commit=False)
                profile.user = user
                profile.save()
                registered = True
            else:
                print(user_form.errors,profile_form.errors)
        else:
            user_form = UserForm()
            profile_form = UserProfileInfoForm()
        return render(request,'accounts/registration.html',
                              {'user_form':user_form,
                               'profile_form':profile_form,
                               'registered':registered})
    except Exception as e:
        return HttpResponse(e, status=500)


def user_login(request):
    """
    performs the users login request
    :param request: includes the user attributes which contains email and password
    :return: if the user's credentials are correct and the user is active returns a welcome message with user's email
             elif user's account is inactive then returns an inactive account message
             else error message is returned with an tried to login other's account
    """
    try:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('index'))
                else:
                    return HttpResponse("Your account was inactive.")
            else:
                print("Someone tried to login and failed.")
                print("They used username: {} and password: {}".format(username,password))
                return HttpResponse("Invalid login details given")
        else:
            return render(request, 'accounts/login.html', {})
    except Exception as e:
        return HttpResponse(e, status=500)


@login_required
def user_logout(request):
    """
    performs logout request
    :param request:
    :return: redirect user to url pattern name index in the url.py file
    """
    try:
        logout(request)
        return HttpResponseRedirect(reverse('index'))
    except Exception as e:
        return HttpResponse(e, status=500)

templates/accounts/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# CloudXTest Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">CloudXTest</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'accounts:register' %}">Register</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'accounts:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/accounts/index.html
{% extends "accounts/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Take Home Assessment !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h3>Login here :</h3>
<form method="post" action="{% url 'accounts:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Email:</label><br>
          <input type="text" name="username" placeholder="Username"><br><br>
<label for="password">Password:</label><br>
          <input type="password" name="password" placeholder="Password"><br><br>
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

templates/accounts/registration.html
{% extends "accounts/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}